# Generated by Django 4.2.6 on 2023-11-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_historicaltask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
    ]
